### ISSUE TITLE
Fatal error: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by mdix** [olihel/grunt-fetch-pages#1]
Job stops with: **Fatal error: Parameter 'url' must be a string, not undefined**. Any suggestions?

Config:

```
dist: {
    options: {
        baseURL: 'http://localhost/',
        destinationFolder: '<%= ROOT_DIR %>/tmp/',
        urls: [
            {
                url: 'http://localhost/de/review/test/table',
                localFile: 'url.html'
            }
        ],
        fetchBaseURL: false

    }
}
```

Console output:

```
Running "fetchpages:dist" (fetchpages) task
Fetching pages...
Creating folders...
  http://localhost/de/review/test/table -> ../../../tmp/url.html
  -> 23025 Bytes
Fatal error: Parameter 'url' must be a string, not undefined
```

Thanks and Best
Marc

Edit: I have to make an addition: It works, but throws the error above. Files are created & have content.

**Comment by olihel** [comment]
Hi Marc,

my guess is there was a "href" attribute missing in your test HTML. Can you verify this?
I just published an updated version of the plugin warning about the issue and preventing an error.

Cheers,
Oliver

**Comment by mdix** [comment]
Hi @olihel,

thanks for your fast response.

Now it reports a missing href value, but still has that error:

```
Running "fetchpages:dist" (fetchpages) task
Fetching pages...
Creating folders...
  http://localhost/de/some/url/form -> ../../../src/some/other/dirs/form.html
  -> 22625 Bytes
following links: skipping link with missing href attribute (<a name="top"></a>)
Fatal error: Parameter 'url' must be a string, not undefined
```

Can I do something to help with the fixing?

Best
Marc
