### ISSUE TITLE
dynamic URLs doesn't work

### ISSUE THREAD

**Issue by etylsarin** [olihel/grunt-fetch-pages#3]
Hi @olihel,

Thanks very much for this useful tool! It works great when URLs array is defined.
Now, I'm dealing with an issue while trying to fetch the pages via links.

my options look like:
options: {
    baseURL: 'http://localhost/Intranet/Snippets',
    destinationFolder: 'snapshots',
    fetchBaseURL: false
}

The page on the provided baseURL contains a list of links in this format:
<a href="http://localhost/Intranet/Snippet?id=Layout">Layout</a>
The query string is dynamically generated.

When I run the fetchpages grunt task, it runs indefinitely with no error.

Have you got any idea what's wrong?

Cheers,
Filip

**Comment by olihel** [comment]
Hi Filip,

thanks for your support, I just pushed a commit that should fix the issue, can you verify this?

Regards,
Oliver

**Comment by etylsarin** [comment]
Hi Oliver,

seems it works now, the only issue is that if you have more links which differ only with the query part of the link, it overwrites each other as the query is not a part of the file name. Anyway, I've updated my links and do not use the query string any more. :)

Regards,
Filip

**Comment by olihel** [comment]
Hi Filip,

you can prevent overwriting of the fetched files by adding a data attribute "localfile" to each link, like so:

``` html
<a href="http://localhost/Intranet/Snippet?id=Layout" data-localfile="layout.html">Layout</a>
<a href="http://localhost/Intranet/Snippet?id=Foo" data-localfile="foo.html">Layout</a>
```

This feature was undocumented to date.

Regards,
Oliver

**Comment by etylsarin** [comment]
Great feature, thanks for letting me know!

Have a good time mate,
Filip
